### ISSUE TITLE
does not build with latest rustc

### ISSUE THREAD

**Issue by matthiaskrgr** [laumann/compiletest-rs#186]
Compiletest does not build with the latest rustc probably due to https://github.com/rust-lang/rust/pull/64663

````
   Compiling compiletest_rs v0.3.22
error[E0063]: missing field `report_time` in initializer of `test::TestOpts`
  --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.22/src/lib.rs:98:5
   |
98 |     test::TestOpts {
   |     ^^^^^^^^^^^^^^ missing `report_time`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0063`.
error: could not compile `compiletest_rs`.
````

**Comment by Manishearth** [comment]
We should probably just pass `report_time: false`, yeah?

**Comment by fenhl** [comment]
I'm now getting this error when trying to compile this crate on the latest nightly:

```
error[E0560]: struct `test::TestOpts` has no field named `report_time`
   --> src/lib.rs:129:9
    |
129 |         report_time: false,
    |         ^^^^^^^^^^^ `test::TestOpts` does not have this field
    |
    = note: available fields are: `list`, `filter`, `filter_exact`, `exclude_should_panic`, `run_ignored` ... and 9 others

```

**Comment by Manishearth** [comment]
This will be automatically fixed in the next nightly, use the previous version of this crate till then.

We fixed the crate for rustc master since we needed that to handle a tangled web of tooling brokenness with Clippy and cargo.

**Comment by fenhl** [comment]
While compiling this crate on its own seems to be fixed on the new nightly, I'm still seeing this issue when trying to run [Rocket](https://github.com/SergioBenitez/Rocket/tree/async)'s `scripts/test.sh`.

```shell-session
$ rustc --version
rustc 1.40.0-nightly (37538aa13 2019-09-25)
```

**Comment by jebrosen** [comment]
This field is not conditioned on `norustc`, which I believe causes the error - Rocket uses the `stable` feature of compiletest.
